#!/usr/bin/env bash

#
# chromium_recover_dbs - Verify & repair chromium sqlite databases
#
# CHANGE LOG:
#
# v0.1   - 2022-01-12 - Morgan Aldridge <morgant@makkintosshu.com>
#                       Initial development.
#
# LICENSE:
#
# Copyright (c) 2022 Morgan Aldridge
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# LICENSE:
#

while IFS= read -r line ; do
  if [[ "$(basename "${line}")" =~ ^(.+)-journal$ ]] ; then
    db="$(dirname "${line}")/${BASH_REMATCH[1]}"
    printf "Checking '%s'... " "${db}"
    result="$(sqlite3 "${db}" "PRAGMA integrity_check;")"
    if [ "${result}" = "ok" ] ; then
      printf "%s\n" "${result}"
    else
      date="$(date +%Y%m%d)"
      printf "\n\tBacking up...\n"
      cp "${db}" "${db}.${date}"
      printf "\tRecovering...\n"
      sqlite3 "${db}.${date}" ".dump" | sqlite3 "${db}.${date}.recovered"
      if [ $? -eq 0 ] ; then
        printf "\tReplacing...\n"
        mv "${db}.${date}.recovered" "${db}"
      fi
    fi
  fi
done <<< "$(find "${HOME}/.config/chromium" -type f -iname "*-journal")"
